fuel_tracker/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, SelectField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    """
    Collects parameters for querying API
    """
    fuel_type_choices = [("BD", "Biodiesel"), ("CNG", "Compressed Natural Gas"),
            ("ELEC", "Electric"), ("E85", "Ethanol (E85)"), ("HY", "Hydrogen"),
            ("LNG", "Liquefied Natural Gas"), ("LPG", "Propane")]

    distance_radius_choices = ["1", "2", "3", "4", "5", "10", "15", "20", "25", "50", "100"]

    address_city_state_zip = StringField("Search Location", validators=[DataRequired()])

    fuel_type = SelectField("Fuel Type", choices=fuel_type_choices, validate_choice=True, default="all", validators=[DataRequired()])

    distance_radius = SelectField("Distance", choices=distance_radius_choices, validate_choice=True, default="5", validators=[DataRequired()])

    submit = SubmitField("Find Stations")

fuel_tracker/__init__.py
from flask import Flask
from fuel_tracker.config import ProductionConfig



def create_app(config_class=ProductionConfig):
    application = Flask(__name__)
    application.config.from_object(config_class)


    from fuel_tracker.routes import main
    application.register_blueprint(main)

    return application

fuel_tracker/routes.py
from flask import render_template, url_for, redirect, Blueprint
from fuel_tracker.config import Config
from fuel_tracker.forms import SearchForm
import requests

main = Blueprint('main', __name__)


@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def home():
    """
    Entry point, handles search form input/submission
    """
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('main.search', form=form))
    return render_template('index.html', form=form)


@main.route("/about")
def about():
    """
    Renders the about page
    """
    return render_template('about.html')


@main.route("/search", methods=['GET', 'POST'])
def search():
    """
    Fetches search results, handles re-search form input/submission
    """
    form = SearchForm()
    if form.validate_on_submit():
        url = generate_url(form.address_city_state_zip.data,
                           form.fuel_type.data, form.distance_radius.data)
        response = requests.get(url).json()
        results_found = response['total_results']
        locations = response['fuel_stations']
        return render_template('index.html', locations=locations, results_found=results_found, form=form)
    return redirect(url_for('main.home', form=form))


@main.route("/directions?origin=<string:origin>&destination=<string:destination>")
def directions(origin, destination):
    """
    Queries Google maps API and opens google maps with route to location
    """
    URL_WITH_KEY = "https://www.google.com/maps/dir/?api=1"
    url = f'{URL_WITH_KEY}&origin={origin}&destination={destination}&travelmode=driving'
    return redirect(url)


# Utility to create API query url
def generate_url(location, fuel_type, range_in_miles):
    """
    Concats the search params to the API url, limited to 25 maximum
    """
    URL_WITH_KEY = f'https://developer.nrel.gov/api/alt-fuel-stations/v1/nearest.json?api_key={str(Config.NREL_API_KEY)}'
    search_query = f'{URL_WITH_KEY}&location={location}&fuel_type={fuel_type}&radius={range_in_miles}&limit=25&access=public'
    return search_query

fuel_tracker/templates/_formhelpers.html
<!--Renders form fields and any errors-->
{% macro render_field(field) %}
  {{ field|safe }}
  {% if field.errors %}
  <div class="invalid-feedback">
    {% for error in field.errors %}
      <span>{{ error }}</span>
    {% endfor %}
  </div>
  {% endif %}
{% endmacro %}

fuel_tracker/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="row ml-3 mr-3">
        <div class="content-section mt-4">
            <h3>About Alternative Fuel Tracker</h3>
            <p>
                AFT helps connect those looking for alternative energy with the stations that carry it. You can find stations within your desired radius, then get directions right to them.
                <br>
                <br>
                To get started, enter a location you'd like to search and see what's out there!
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <small>AFT is proudly powered by Google APIs and the National Renewable Energy Labs API.</small>
            </p>
        </div>
    </div>
{% endblock content %}

fuel_tracker/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"></link>
    <title>Alternative Fuel Tracker</title>
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark">
      <div class="container">
        <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}"><strong>Alternative Fuel Tracker</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Search</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
          {% block content %}
          {% endblock %}
  </main>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6QGWmRXuMvMUeR63Cq9Xp1qbXK8Le058&callback=initMap&libraries=&v=weekly" async></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

fuel_tracker/templates/index.html
{% extends "base.html" %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
  <div class="row ml-3 mr-3">
    <div class="col-xs-12 pb-2">
        <div class="content-section mt-4">
          <h5>Enter an adresss, city/state, or zip. Then select your desired fuel type and max distance.</h5>
          <form class="form-inline" method="POST" action="{{ url_for('main.search') }}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <div class="form-group">
                {{ form.address_city_state_zip.label(class="form-control-label mr-2") }}
                {{ render_field(form.address_city_state_zip(class="form-control form-control-md mr-3")) }}
              </div>
              <div class="form-group">
                {{ form.fuel_type.label(class="form-control-label mr-2") }}
                {{ render_field(form.fuel_type(class="form-control form-control-md mr-3")) }}
              </div>
              <div class="form-group">
                {{ form.distance_radius.label(class="form-control-label mr-2") }}
                {{ render_field(form.distance_radius(class="form-control form-control-md mr-5")) }}
              </div>
            <div class="form-group">
              {{ form.submit(class="btn btn-secondary") }}
            </div>
            </fieldset>
          </form>
        </div>
    </div>
  </div>
  <div class="row ml-1 mr-1">
    <div class="col-sm-5 pr-3">
      <div class="scroll">
        {% if form.validate_on_submit() %}
        {% if results_found %}
        <div class="content-section mt-3">
          <h3> {{results_found}} stations found near {{ form.address_city_state_zip.data }}</h3>
            <ul class="list-group" id="stationsResult">
              {% for location in locations %}
              <article class="media">
                <div class="media-body">
                  <h5>
                    <strong name="placeName">{{ location["station_name"] }}</strong>
                    <small> (Last confirmed: {{ location["date_last_confirmed"] }})</small>
                  </h5>
                  <hr>
                  <p name="placeAddress">
                    {{ location["street_address"] }}, {{ location["city"] }}, {{ location["state"]}} , {{ location["zip"] }}
                  </p>
                  <div class="text-right">
                    <strong>{{ "%.2f"|format(location["distance"]) }}</strong> miles
                    <a href="{{ url_for('main.directions', origin=form.address_city_state_zip.data,
                      destination=location['street_address'] +' '+ location['city'] +' '+ location['state']
                      +' '+ location['zip']) }}" target="_blank">
                      <button type="button" class="btn btn-sm btn-light">Directions</button>
                    </a>
                    </div>
                </div>
              </article>
              {% endfor %}
            </ul>
        </div>
        {% else %}
        <div class="content-section mt-3">
          <h5>No results found</h5>
        </div>
        {% endif %}
        {% endif %}
      </div>
    </div>
    <div class="col-sm-7">
        <div id="map"></div>
    </div>
  </div>
{% endblock %}